version: '3'
services:
  broker:
    container_name: go-broker
    restart: always
    build: ./Broker
    ports:
      - '43200:${BROKER_TCP_PORT}'
      - '43201:${BROKER_GRPC_PORT}'
    depends_on:
      - mongo
      - redis
    networks:
      - message-broker
networks:
  message-broker:
